# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Main_Card.xdc

# Block Designs: bd/Main_Card/Main_Card.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Main_Card || ORIG_REF_NAME==Main_Card} -quiet] -quiet

# IP: bd/Main_Card/ip/Main_Card_processing_system7_0_0/Main_Card_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Main_Card_processing_system7_0_0 || ORIG_REF_NAME==Main_Card_processing_system7_0_0} -quiet] -quiet

# IP: bd/Main_Card/ip/Main_Card_canfd_0_0/Main_Card_canfd_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Main_Card_canfd_0_0 || ORIG_REF_NAME==Main_Card_canfd_0_0} -quiet] -quiet

# IP: bd/Main_Card/ip/Main_Card_canfd_1_0/Main_Card_canfd_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Main_Card_canfd_1_0 || ORIG_REF_NAME==Main_Card_canfd_1_0} -quiet] -quiet

# IP: bd/Main_Card/ip/Main_Card_clk_wiz_1_0/Main_Card_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Main_Card_clk_wiz_1_0 || ORIG_REF_NAME==Main_Card_clk_wiz_1_0} -quiet] -quiet

# IP: bd/Main_Card/ip/Main_Card_xlconcat_0_0/Main_Card_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Main_Card_xlconcat_0_0 || ORIG_REF_NAME==Main_Card_xlconcat_0_0} -quiet] -quiet

# IP: bd/Main_Card/ip/Main_Card_GPS_Synchronizer_0_1/Main_Card_GPS_Synchronizer_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Main_Card_GPS_Synchronizer_0_1 || ORIG_REF_NAME==Main_Card_GPS_Synchronizer_0_1} -quiet] -quiet

# IP: bd/Main_Card/ip/Main_Card_ps7_0_axi_periph_2/Main_Card_ps7_0_axi_periph_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Main_Card_ps7_0_axi_periph_2 || ORIG_REF_NAME==Main_Card_ps7_0_axi_periph_2} -quiet] -quiet

# IP: bd/Main_Card/ip/Main_Card_rst_ps7_0_100M_0/Main_Card_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Main_Card_rst_ps7_0_100M_0 || ORIG_REF_NAME==Main_Card_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Main_Card/ip/Main_Card_RTC_Synchronizer_0_0/Main_Card_RTC_Synchronizer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Main_Card_RTC_Synchronizer_0_0 || ORIG_REF_NAME==Main_Card_RTC_Synchronizer_0_0} -quiet] -quiet

# IP: bd/Main_Card/ip/Main_Card_xbar_0/Main_Card_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Main_Card_xbar_0 || ORIG_REF_NAME==Main_Card_xbar_0} -quiet] -quiet

# IP: bd/Main_Card/ip/Main_Card_auto_pc_0/Main_Card_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Main_Card_auto_pc_0 || ORIG_REF_NAME==Main_Card_auto_pc_0} -quiet] -quiet

# XDC: bd/Main_Card/Main_Card_ooc.xdc
