# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Vebko/Relay/Relay_V3.0/Rev.02/Main_Card_Zynq7020/Main/Main_Card_ZYNQ7020/Main_Card_ZYNQ7020.srcs/sources_1/bd/Main_Card/ip/Main_Card_xbar_0/Main_Card_xbar_0.xci
# IP: The module: 'Main_Card_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vebko/Relay/Relay_V3.0/Rev.02/Main_Card_Zynq7020/Main/Main_Card_ZYNQ7020/Main_Card_ZYNQ7020.srcs/sources_1/bd/Main_Card/ip/Main_Card_xbar_0/Main_Card_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Main_Card_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Vebko/Relay/Relay_V3.0/Rev.02/Main_Card_Zynq7020/Main/Main_Card_ZYNQ7020/Main_Card_ZYNQ7020.srcs/sources_1/bd/Main_Card/ip/Main_Card_xbar_0/Main_Card_xbar_0.xci
# IP: The module: 'Main_Card_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vebko/Relay/Relay_V3.0/Rev.02/Main_Card_Zynq7020/Main/Main_Card_ZYNQ7020/Main_Card_ZYNQ7020.srcs/sources_1/bd/Main_Card/ip/Main_Card_xbar_0/Main_Card_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Main_Card_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
